name: konsumer_core
description: "Riverpod widgets for building UI and reacting to notifier state changes through builder, listener, and first-frame callbacks with direct access to state, notifier, and WidgetRef."
version: 0.0.5
repository: https://github.com/Rune-Shift/dart_kit/tree/main/packages/konsumer_core

resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: <=11.0.0