name: sherlog
description: "A developer-friendly logging utility for Dart and Flutter with clean, readable formatting, structured output, configurable log levels, and a simple API for everyday development."
version: 1.0.3
repository: https://github.com/Rune-Shift/dart_kit/tree/main/packages/sherlog

resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  logger: ^2.5.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: <=11.0.0
