name: dart_oxide
description: "Rust inspired sum types for dart."
version: 0.1.7

resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: <=11.0.0
