name: statetris
description: "A state handling package"
version: 0.0.6

resolution: workspace

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: <=11.0.0